spring.datasource.url=jdbc:postgresql://dpg-d78vipnkijhs738kldrg-a.virginia-postgres.render.com:5432/myblogapp_l8pj
spring.datasource.username=myblogapp_l8pj_user
spring.datasource.password=yDnXPIKTvY0HaPAo5ID2ZpAVi3XGRFBl
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true